name: Déploiement d'application Python

# Déclencheur
on:
  push:
    branches:
      - main

# Variables globales
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# Jobs
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Permissions
    permissions:
      contents: read # droit sur le repo
      packages: write # droit d'écrire des packages ghcr.io (images docker)

    # Étapes
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Connexion au registre GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build et Push de l'image Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
